### ISSUE TITLE
No matter where I look, I cannot seem to find MaliitPluginsConfig.cmake, which CMake demands

### ISSUE THREAD

**Issue by CheetahPixie** [maliit/keyboard#75]
It's not in this source tree, it's not in that of frameworks, it's not in plugins, and it's in none of the -dev packages I have so far tried on Kubuntu Impish Indri.

Do you guys perhaps have *any* build instructions? Because none exist in this repository either.

**Comment by dobey** [comment]
Have you installed https://github.com/maliit/framework to some alternate prefix perhaps?

**Comment by CheetahPixie** [comment]
I haven't built it at all, since I expected there to be the relevant cmake file in a -dev package somewhere. Do I need that built as well?

**Comment by dobey** [comment]
> I haven't built it at all, since I expected there to be the relevant cmake file in a -dev package somewhere. Do I need that built as well?

Yes. The maliit-framework in Ubuntu is quite old (and I'm not sure why it's even still in there). The 2.x versions have not been packaged for Debian nor Ubuntu yet. It is what provides libmaliit-plugins that is needed, as well as the pkgconfig and cmake files.

Since this seems to be the problem here, I'm going to close this. There are already some other open issues about improving documentation in this regard, such as #30 and #35 .

Thanks.

**Comment by CheetahPixie** [comment]
ahh. alright.

Should probably make a mention of this somewhere so people like me don't run into the same confusion/issues. I'm trying to figure out the dependencies currently for the framework, and I'll see where I can go from there. Thanks for entertaining some user error.
